<?xml version='1.0' encoding='UTF-8'?>
<org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage_-Tag plugin="workflow-support@2.14">
  <node class="org.jenkinsci.plugins.workflow.cps.nodes.StepEndNode" plugin="workflow-cps@2.32">
    <parentIds>
      <string>9</string>
    </parentIds>
    <id>10</id>
    <startId>3</startId>
  </node>
  <actions>
    <org.jenkinsci.plugins.workflow.actions.ErrorAction plugin="workflow-api@2.16">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@2.12">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:951)</trace>
          <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2$1.run(WorkflowRun.java:276)</trace>
          <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
          <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
          <trace>java.lang.Thread.run(Thread.java:748)</trace>
        </stackTrace>
        <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
          <c class="list"/>
          <list reference="../c"/>
        </suppressedExceptions>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <jenkins.model.CauseOfInterruption_-UserInterruption>
              <user>anonymous</user>
            </jenkins.model.CauseOfInterruption_-UserInterruption>
          </a>
        </causes>
      </error>
    </org.jenkinsci.plugins.workflow.actions.ErrorAction>
    <org.jenkinsci.plugins.workflow.actions.TimingAction plugin="workflow-api@2.16">
      <startTime>1506117028396</startTime>
    </org.jenkinsci.plugins.workflow.actions.TimingAction>
    <org.jenkinsci.plugins.workflow.actions.ErrorAction plugin="workflow-api@2.16">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" reference="../../org.jenkinsci.plugins.workflow.actions.ErrorAction/error"/>
    </org.jenkinsci.plugins.workflow.actions.ErrorAction>
  </actions>
</org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage_-Tag>